### ISSUE TITLE
请问ro.ril.oem.imei这个值是怎么来的

### ISSUE THREAD

**Issue by wuliao6688** [UiharuNeko/Xiaomi_IMEI_Hide#1]
我搜索了  AOSP的源码  并没有发现  有这个相关代码

**Comment by UiharuNeko** [comment]
因为这不是AOSP的东西，是MIUI自己加的，因此只有小米的设备才会有这种情况（其他厂家可能有别的情况

**Comment by wuliao6688** [comment]
但我查了  Mokee也没有发现相关代码  但是他的系统开机之后也有这个值

**Comment by UiharuNeko** [comment]
因为压根不是系统的问题（
只要用的是小米提供的firmware，都会有这个

**Comment by wuliao6688** [comment]
也就是这个值是从kernel里来的是吗
